const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#arcade'),ctx=canvas.getContext('2d'),bullImg=new Image();bullImg.src='assets/reference-bull.webp';
const state={running:false,paused:false,score:0,streak:0,level:1,best:Number(localStorage.getItem('ansemArcadeBest')||0),shield:3,x:210,y:405,targetX:210,targetY:405,items:[],particles:[],last:0,spawn:0,road:0,muted:false,keys:new Set()};
const hud=()=>{$('#a-score').textContent=String(state.score).padStart(5,'0');$('#a-streak').textContent=`${state.streak}×`;$('#a-level').textContent=String(state.level).padStart(2,'0');$('#a-best').textContent=String(state.best).padStart(5,'0');$('#a-shield').textContent='●'.repeat(state.shield)+'○'.repeat(3-state.shield);$('#mission').textContent=state.streak>=10?'MISSION COMPLETE: BUY BOOST UNLOCKED':'MISSION: Reach a 10× streak';};
const tone=(freq=300,duration=.07)=>{if(state.muted)return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;o.type='square';g.gain.value=.025;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+duration);o.stop(a.currentTime+duration);}catch{}};
function reset(){Object.assign(state,{running:true,paused:false,score:0,streak:0,level:1,shield:3,x:210,y:405,targetX:210,targetY:405,items:[],particles:[],last:performance.now(),spawn:0});$('#arcade-overlay').classList.add('is-hidden');hud();}
function spawn(t){const gap=Math.max(310,760-state.level*42);if(t-state.spawn<gap)return;state.spawn=t;const roll=Math.random(),type=roll<.62?'candle':roll<.86?'rug':roll<.95?'shield':'rocket';state.items.push({type,x:1510,y:145+Math.random()*520,size:type==='rug'?56:38,speed:7+state.level*.55+Math.random()*3,spin:0});}
function burst(x,y,color,count=12){for(let i=0;i<count;i++)state.particles.push({x,y,vx:(Math.random()-.5)*12,vy:(Math.random()-.5)*12,life:1,color});}
function drawRoad(){const horizon=150;ctx.fillStyle='#010301';ctx.fillRect(0,0,canvas.width,canvas.height);const sky=ctx.createRadialGradient(720,horizon,20,720,horizon,720);sky.addColorStop(0,'rgba(157,255,34,.18)');sky.addColorStop(1,'transparent');ctx.fillStyle=sky;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#050a05';ctx.beginPath();ctx.moveTo(560,horizon);ctx.lineTo(880,horizon);ctx.lineTo(1420,810);ctx.lineTo(20,810);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(157,255,34,.22)';ctx.lineWidth=3;for(let i=-7;i<=7;i++){ctx.beginPath();ctx.moveTo(720+i*23,horizon);ctx.lineTo(720+i*110,810);ctx.stroke();}state.road=(state.road+12+state.level)%80;for(let y=horizon+state.road;y<900;y+=80){const p=(y-horizon)/(810-horizon);ctx.globalAlpha=p*.45;ctx.beginPath();ctx.moveTo(560-540*p,y);ctx.lineTo(880+540*p,y);ctx.stroke();}ctx.globalAlpha=1;}
function drawBull(){ctx.save();ctx.translate(state.x,state.y);const bob=Math.sin(performance.now()/70)*5;ctx.shadowColor='#9dff22';ctx.shadowBlur=30;ctx.drawImage(bullImg,-112,-76+bob,230,150);ctx.shadowBlur=0;ctx.fillStyle='#9dff22';ctx.fillRect(-62,66+bob,95,5);ctx.restore();}
function drawItem(o){ctx.save();ctx.translate(o.x,o.y);o.spin+=.06;ctx.rotate(o.spin);ctx.shadowBlur=24;if(o.type==='candle'){ctx.shadowColor=ctx.fillStyle='#9dff22';ctx.fillRect(-10,-28,20,56);ctx.fillRect(-2,-40,4,80);}else if(o.type==='rug'){ctx.shadowColor=ctx.fillStyle='#ff355d';ctx.fillRect(-42,-25,84,50);ctx.fillStyle='#120207';ctx.font='800 18px JetBrains Mono';ctx.fillText('RUG',-20,7);}else if(o.type==='shield'){ctx.strokeStyle='#41f6ff';ctx.shadowColor='#41f6ff';ctx.lineWidth=7;ctx.beginPath();ctx.arc(0,0,30,0,Math.PI*2);ctx.stroke();}else{ctx.fillStyle=ctx.shadowColor='#ffd76f';ctx.beginPath();ctx.moveTo(34,0);ctx.lineTo(-25,-22);ctx.lineTo(-12,0);ctx.lineTo(-25,22);ctx.closePath();ctx.fill();}ctx.restore();}
const hit=o=>Math.abs(o.x-state.x)<95&&Math.abs(o.y-state.y)<70;
function end(){state.running=false;state.best=Math.max(state.best,state.score);localStorage.setItem('ansemArcadeBest',state.best);hud();const ov=$('#arcade-overlay');ov.classList.remove('is-hidden');ov.querySelector('p').textContent='RUN COMPLETE';ov.querySelector('h1').innerHTML=`${state.score}<br><em>POINTS</em>`;ov.querySelector('span').textContent=`Level ${state.level} · Best ${state.best} · ${state.streak>=10?'Buy boost unlocked':'Run it back for a 10× streak'}`;$('#play-game').textContent='RUN IT BACK';}
function update(t,dt){if(!state.running||state.paused)return;spawn(t);const move=460*dt;if(state.keys.has('ArrowUp')||state.keys.has('w'))state.targetY-=move;if(state.keys.has('ArrowDown')||state.keys.has('s'))state.targetY+=move;if(state.keys.has('ArrowLeft')||state.keys.has('a'))state.targetX-=move;if(state.keys.has('ArrowRight')||state.keys.has('d'))state.targetX+=move;state.targetX=Math.max(130,Math.min(620,state.targetX));state.targetY=Math.max(145,Math.min(700,state.targetY));state.x+=(state.targetX-state.x)*.13;state.y+=(state.targetY-state.y)*.13;for(const o of state.items){o.x-=o.speed*(dt*60);if(hit(o)&&!o.hit){o.hit=true;if(o.type==='candle'){state.streak++;state.score+=100*state.streak;burst(o.x,o.y,'#9dff22',18);tone(420+state.streak*25);}else if(o.type==='shield'){state.shield=Math.min(3,state.shield+1);burst(o.x,o.y,'#41f6ff',20);tone(760);}else if(o.type==='rocket'){state.score+=1000;state.streak+=2;burst(o.x,o.y,'#ffd76f',28);tone(950);}else{state.shield--;state.streak=0;burst(o.x,o.y,'#ff355d',25);tone(90,.18);if(state.shield<=0)end();}state.level=1+Math.floor(state.score/3500);state.best=Math.max(state.best,state.score);hud();}}state.items=state.items.filter(o=>!o.hit&&o.x>-100);for(const p of state.particles){p.x+=p.vx;p.y+=p.vy;p.life-=.035;}state.particles=state.particles.filter(p=>p.life>0);}
function loop(t){const dt=Math.min(.03,(t-state.last)/1000||.016);state.last=t;drawRoad();state.items.forEach(drawItem);drawBull();for(const p of state.particles){ctx.globalAlpha=p.life;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,5,5);}ctx.globalAlpha=1;if(state.paused){ctx.fillStyle='rgba(0,0,0,.55)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#fff';ctx.font='800 72px Bebas Neue';ctx.textAlign='center';ctx.fillText('PAUSED',720,420);ctx.textAlign='left';}update(t,dt);requestAnimationFrame(loop);}
$('#play-game').addEventListener('click',reset);$('#pause-game').addEventListener('click',()=>{if(!state.running)return;state.paused=!state.paused;$('#pause-game').textContent=state.paused?'▶':'Ⅱ';});$('#mute-game').addEventListener('click',()=>{state.muted=!state.muted;$('#mute-game').textContent=`SOUND: ${state.muted?'OFF':'ON'}`;});
window.addEventListener('keydown',e=>{state.keys.add(e.key);if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();});window.addEventListener('keyup',e=>state.keys.delete(e.key));canvas.addEventListener('pointermove',e=>{if(!state.running)return;const r=canvas.getBoundingClientRect();state.targetX=(e.clientX-r.left)/r.width*canvas.width;state.targetY=(e.clientY-r.top)/r.height*canvas.height;});$$('[data-move]').forEach(b=>{const key={up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight'}[b.dataset.move];b.addEventListener('pointerdown',()=>state.keys.add(key));b.addEventListener('pointerup',()=>state.keys.delete(key));});hud();requestAnimationFrame(loop);
