const MINT = '9cRCn9rGT8V2imeM2BaKs13yhMEais3ruM3rPvTGpump';
const API = `https://api.dexscreener.com/latest/dex/tokens/${MINT}`;
const BUY = `https://jup.ag/swap/SOL-${MINT}`;
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const money = (n) => { n=Number(n); if(!Number.isFinite(n))return '--'; if(n<0.01)return `$${n.toFixed(6)}`; return `$${new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:2}).format(n)}`; };
const number = (n) => new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(Number(n)||0);
let pairs=[], selected, range='h24';
$$('[data-buy]').forEach((a)=>a.href=BUY);
function setText(id,text){const el=$(id);if(el)el.textContent=text;}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('is-visible');setTimeout(()=>t.classList.remove('is-visible'),1800);}
function setChart(pair){selected=pair;const url=`https://dexscreener.com/solana/${pair.pairAddress}`;$('#dex-link').href=url;$('#dex-chart').src=`${url}?embed=1&theme=dark&trades=0&info=0`;setText('#chart-pair',`${pair.baseToken.symbol} / ${pair.quoteToken.symbol}`);renderFlow();}
function renderFlow(){if(!selected)return;const tx=selected.txns?.[range]||{},buys=Number(tx.buys||0),sells=Number(tx.sells||0),total=buys+sells,pct=total?Math.round(buys/total*100):50;$('#flow-ring').style.setProperty('--buy',pct);setText('#flow-percent',`${pct}%`);setText('#flow-buys',number(buys));setText('#flow-sells',number(sells));setText('#flow-volume',money(selected.volume?.[range]));const change=Number(selected.priceChange?.[range]||0);setText('#flow-change',`${change>=0?'+':''}${change.toFixed(2)}%`);}
function renderPools(){ $('#pool-rows').innerHTML=pairs.slice(0,12).map((p,i)=>{const tx=(p.txns?.h24?.buys||0)+(p.txns?.h24?.sells||0);return `<button class="pool-row" data-pair="${i}"><span><b>${p.baseToken.symbol}/${p.quoteToken.symbol}</b><small>${p.pairAddress.slice(0,5)}…${p.pairAddress.slice(-4)}</small></span><span>${p.dexId.toUpperCase()}${p.labels?.[0]?` · ${p.labels[0]}`:''}</span><span>${money(p.liquidity?.usd)}</span><span>${money(p.volume?.h24)}</span><span>${number(tx)}</span><span>View ↗</span></button>`;}).join('');$$('#pool-rows [data-pair]').forEach(b=>b.addEventListener('click',()=>{setChart(pairs[Number(b.dataset.pair)]);window.scrollTo({top:$('#chart').offsetTop-90,behavior:'smooth'});}));}
async function hydrate(){try{const res=await fetch(API,{headers:{accept:'application/json'}});if(!res.ok)throw new Error(res.status);const data=await res.json();pairs=(data.pairs||[]).filter(p=>p.chainId==='solana'&&Number(p.liquidity?.usd||0)>0).sort((a,b)=>Number(b.liquidity?.usd||0)-Number(a.liquidity?.usd||0));if(!pairs.length)throw new Error('No active pools');const best=pairs[0],change=Number(best.priceChange?.h24||0),tx=(best.txns?.h24?.buys||0)+(best.txns?.h24?.sells||0),totalLiq=pairs.reduce((s,p)=>s+Number(p.liquidity?.usd||0),0),buys=Number(best.txns?.h24?.buys||0),sells=Number(best.txns?.h24?.sells||0);setText('#t-price',money(best.priceUsd));setText('#t-change',`${change>=0?'+':''}${change.toFixed(2)}% · 24H`);$('#t-change').className=change>=0?'positive':'negative';setText('#t-updated',`Updated ${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`);setText('#t-mcap',money(best.marketCap||best.fdv));setText('#t-liq',money(totalLiq));setText('#t-vol',money(best.volume?.h24));setText('#t-txns',number(tx));setText('#t-ratio',`${buys}:${sells}`);if(!selected)setChart(best);else selected=pairs.find(p=>p.pairAddress===selected.pairAddress)||best;renderFlow();renderPools();}catch{setText('#t-change','Live feed unavailable — use DexScreener');$('#t-change').className='negative';}}
$('#range-tabs').addEventListener('click',(e)=>{const b=e.target.closest('button');if(!b)return;range=b.dataset.range;$$('#range-tabs button').forEach(x=>x.classList.toggle('is-active',x===b));renderFlow();});
$('#terminal-copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(MINT);toast('Contract address copied');}catch{toast('Select and copy the address above');}});
hydrate();setInterval(hydrate,30000);
